class AppRoute {
  AppRoute._();
  static const mainTab = '/mainTab';
  static const components = '/components';
  static const login = '/login';
  static const home = '/home';
  static const createMerchant = '/createMerchant';
  static const merchantDetail = '/merchantDetail';
  static const editMerchantInfo = '/editMerchantInfo';
  static const editIdentityInfo = '/editIdentityInfo';
  static const editMerchantNote = '/editMerchantNote';
  static const editBankInfo = '/editBankInfo';
  static const createNewStore = '/createNewStore';
  static const attachMerchantVA = '/attachMerchantVA';
  static const scanQR = '/scanQR';
  static const storeDetail = '/storeDetail';
  static const vaDetail = '/vaDetail';
  static const updateVaName = '/updateVaName';
  static const changeVADevice = '/changeVADevice';
  static const attachDevice = '/attachDevice';
  static const createEnterprise = '/createEnterprise';
  static const mcLatePayment = '/mcLatePayment';
  static const vaLock = '/vaLock';
  static const mcvaLatePayment = '/mcvaLatePayment';
  static const deiceDetail = '/deiceDetail';
  static const addDevice = '/addDevice';
  static const selectedSub = '/selectedSub';
  static const editNameVa = '/editNameVa';
  static const linkDeviceAgent = '/linkDeviceAgent';
  static const addLocation = '/addLocation';
}
